//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAS
    {
        public int IDCOMPRA { get; set; }
        public string FACTURA { get; set; }
        public Nullable<int> IDREF { get; set; }
        public double CANT { get; set; }
        public double VALCOSTO_UNI { get; set; }
        public string PROVEEDOR { get; set; }
        public double MONTO_TOTAL { get; set; }
        public string TIPO { get; set; }
        public System.DateTime FECHACOMPRA { get; set; }
        public System.DateTime FECHAPAGO { get; set; }
        public int IDPROVEEDOR { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        public virtual REFERENCIAS REFERENCIAS { get; set; }
    }
}
