//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int IIDEMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHACONTRATO { get; set; }
        public Nullable<double> SUELDO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public int IDUSUARIO { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public string TIPOUSUARIO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual TIPOUSUARIOREGISTRO TIPOUSUARIOREGISTRO { get; set; }
    }
}
