//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GASTOS
    {
        public string COMPROVANTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DESCRIPCION { get; set; }
        public double MONTO { get; set; }
        public string BENEFICIARIO { get; set; }
        public string NUIP { get; set; }
        public string DESCRIPCION_DETALLADA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    }
}
