//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRODIARIO
    {
        public double VENTAS { get; set; }
        public double COMPRAS { get; set; }
        public double GASTOS { get; set; }
        public double VENTASCRED { get; set; }
        public double AB_COMPRAS { get; set; }
        public double UTILIDAD { get; set; }
        public System.DateTime FECHA { get; set; }
    }
}
