//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class URBANEntities : DbContext
    {
        public URBANEntities()
            : base("name=URBANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ABONOSCOMPRASCREDITO> ABONOSCOMPRASCREDITO { get; set; }
        public DbSet<ABONOSVENTASCREDITO> ABONOSVENTASCREDITO { get; set; }
        public DbSet<CARROS> CARROS { get; set; }
        public DbSet<CLIENTES> CLIENTES { get; set; }
        public DbSet<COMPRAS> COMPRAS { get; set; }
        public DbSet<COMPRASCREDITO> COMPRASCREDITO { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<ITEMS> ITEMS { get; set; }
        public DbSet<PROVEEDORES> PROVEEDORES { get; set; }
        public DbSet<REFERENCIAS> REFERENCIAS { get; set; }
        public DbSet<RUTA> RUTA { get; set; }
        public DbSet<Tbl_Category> Tbl_Category { get; set; }
        public DbSet<Tbl_TIPO> Tbl_TIPO { get; set; }
        public DbSet<TIPOUSUARIOREGISTRO> TIPOUSUARIOREGISTRO { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VENTA_PROD> VENTA_PROD { get; set; }
        public DbSet<VENTA_PRODWEB> VENTA_PRODWEB { get; set; }
        public DbSet<VENTASCREDITO> VENTASCREDITO { get; set; }
        public DbSet<DEVCOMPRAS> DEVCOMPRAS { get; set; }
        public DbSet<DEVENTA_PROD> DEVENTA_PROD { get; set; }
        public DbSet<GASTOS> GASTOS { get; set; }
        public DbSet<LIBRODIARIO> LIBRODIARIO { get; set; }
    }
}
