//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORES
    {
        public PROVEEDORES()
        {
            this.ABONOSCOMPRASCREDITO = new HashSet<ABONOSCOMPRASCREDITO>();
            this.COMPRAS = new HashSet<COMPRAS>();
        }
    
        public int IDPROVEEDOR { get; set; }
        public string PROVEEDOR { get; set; }
        public string NUIP { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CIUDAD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual ICollection<ABONOSCOMPRASCREDITO> ABONOSCOMPRASCREDITO { get; set; }
        public virtual ICollection<COMPRAS> COMPRAS { get; set; }
    }
}
