//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Category
    {
        public Tbl_Category()
        {
            this.REFERENCIAS = new HashSet<REFERENCIAS>();
        }
    
        public int CategoryId { get; set; }
        public string NombreCategoria { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual ICollection<REFERENCIAS> REFERENCIAS { get; set; }
    }
}
