//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOUSUARIOREGISTRO
    {
        public TIPOUSUARIOREGISTRO()
        {
            this.CLIENTES = new HashSet<CLIENTES>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
            this.USUARIOS = new HashSet<USUARIOS>();
            this.USUARIOS1 = new HashSet<USUARIOS>();
        }
    
        public string TIPOUSUARIO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
        public virtual ICollection<USUARIOS> USUARIOS1 { get; set; }
    }
}
