//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.ABONOSVENTASCREDITO = new HashSet<ABONOSVENTASCREDITO>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
        }
    
        public int IDUSUARIO { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public string TIPOUSUARIO { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public Nullable<int> IID { get; set; }
    
        public virtual ICollection<ABONOSVENTASCREDITO> ABONOSVENTASCREDITO { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        public virtual TIPOUSUARIOREGISTRO TIPOUSUARIOREGISTRO { get; set; }
        public virtual TIPOUSUARIOREGISTRO TIPOUSUARIOREGISTRO1 { get; set; }
    }
}
