//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_PRODWEB
    {
        public int IDWEB { get; set; }
        public int IDREF { get; set; }
        public string DESCRIPCION { get; set; }
        public double VALUNI_VENTA { get; set; }
        public double CANT { get; set; }
        public double MONTO_TOTAL { get; set; }
        public string TIPO { get; set; }
        public System.DateTime FECHAVENTA { get; set; }
        public string USUARIO { get; set; }
        public string CLIENTE { get; set; }
        public string DIRECCION { get; set; }
        public int TELEFONO { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual REFERENCIAS REFERENCIAS { get; set; }
    }
}
