//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URBAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_PROD
    {
        public VENTA_PROD()
        {
            this.DEVENTA_PROD = new HashSet<DEVENTA_PROD>();
        }
    
        public string IDVENTA { get; set; }
        public string REMISION { get; set; }
        public Nullable<int> IDREF { get; set; }
        public string DESCRIPCION { get; set; }
        public string NUIP { get; set; }
        public double VALUNI_VENTA { get; set; }
        public double CANT { get; set; }
        public double MONTO_TOTAL { get; set; }
        public string TIPO { get; set; }
        public System.DateTime FECHAVENTA { get; set; }
        public System.DateTime FECHAPAGO { get; set; }
        public int IDCLIENTE { get; set; }
        public Nullable<double> UTILIDAD { get; set; }
        public string USUARIO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual REFERENCIAS REFERENCIAS { get; set; }
        public virtual ICollection<DEVENTA_PROD> DEVENTA_PROD { get; set; }
    }
}
